kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: {{ .Values.postgres.ressources.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.postgres.ressources.storage }}
