kind: PersistentVolume
apiVersion: v1
metadata:
  name: web-pv
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: {{ .Values.adminer.ressources.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/web"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.adminer.ressources.storage }}
