apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: webapp
    tier: database
  ports:
    - name: postgres-port
      port: 5432
      protocol: TCP
