apiVersion: v1
kind: Pod
metadata:
  name: adminer-pod
  labels:
    app: webapp
    tier: frontend
  namespace: default
spec:
  containers:
    - name: adminer-container
      image: adminer
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 500m
          memory: 200Mi
        limits:
          cpu: 1000m
          memory: 600Mi
      env:
        - name: ADMINER_DESIGN
          value: "pappu687"

  restartPolicy: Always
